### ISSUE TITLE
Two finger right (click)

### ISSUE THREAD

**Issue by Ra-Pad** [whot/kcm_touchpad#1]
Two-finger-tap right click works great but when I press the trackpad with two fingers (until it clicks) it left clicks.
Is there a way to fix this, or could you make a update that has this fix?

I'd greatly appreciate it, thanks!

**Comment by whot** [comment]
sorry, this repository is dead, I used it years ago for the original libinput-support implementation but haven't touched it since.  If it's to do with actual touchpad functionality, please file the bug with libinput. if it's to do with configuration, please file against the upstream kcm_touchpad repository.
